name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  push:
    branches:
      - main
      # - ci-updates # if testing is required (create branch called ci-updates)

permissions:
  id-token: write # Required for OIDC authentication (workload identity provider)
  contents: read # Required to read the repo content

jobs:
  publish:
    name: Publish
    uses: "joepk90/serverless-apps-ci-workflows/.github/workflows/shared-publish.yaml@main"
    secrets: inherit

  deploy:
    name: Deploy
    uses: "joepk90/serverless-apps-ci-workflows/.github/workflows/shared-deploy.yaml@main"
    needs: publish
    secrets: inherit
